<a href="https://colab.research.google.com/github/rajgit-123/python-repo/blob/main/day8of45_python_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#working with groupby and aggregations

In [ ]:
import pandas as pd
sales=pd.DataFrame({
    'weekday' :['Sun','Sun','Mon','Mon'],
    'city':['Austin','Dallas','Austin','Dallas'],
    'bread':[139,237,326,456],
    'butter':[20,45,70,98]

})
sales

  weekday    city  bread  butter
0     Sun  Austin    139      20
1     Sun  Dallas    237      45
2     Mon  Austin    326      70
3     Mon  Dallas    456      98

In [ ]:
#boolean filter count
sales.loc[sales['weekday']=='Sun'].count()

#groupby Count
sales.groupby('weekday').count()

#groupby and sum
sales.groupby('weekday')['bread'].sum()

sales.groupby('weekday')['butter'].sum()
#group by and sum on multiple columns
sales.groupby('weekday')[['bread','butter']].sum()

#groupny and mean :multilevel index
sales.groupby(['city','weekday']).mean()
#sales.groupby(['bread','weekday']).mean()

#groupby and max on multiple coulmns
sales.groupby('weekday')[['bread','butter']].max()
#sales.groupby(['city','weekday']).max()

##multiple aggregations
sales.groupby('city')[['bread','butter']].agg(['max','min'])

#custom aggregation
def data_range(series):
  return series.max()-series.min()
sales.groupby('weekday')[['bread','butter']].agg(data_range)

         bread  butter
weekday
Mon        130      28
Sun         98      25